import type { AccessPermission, Branch, BranchId, Department, Device, Incident, MaintenanceEvent, OrganizationUnit, UserAccount } from './types'

export const hospitalName = 'Bệnh viện Đa khoa Xuyên Á'

export const branches: Branch[] = [
  { id: 'cu-chi', name: 'BV Xuyên Á Củ Chi', shortName: 'Củ Chi', region: 'TP. Hồ Chí Minh', inventoryCount: 64 },
  { id: 'tay-ninh', name: 'BV Xuyên Á Tây Ninh', shortName: 'Tây Ninh', region: 'Tây Ninh', inventoryCount: 39 },
  { id: 'long-an', name: 'BV Xuyên Á Long An', shortName: 'Long An', region: 'Long An', inventoryCount: 36 },
  { id: 'vinh-long', name: 'BV Xuyên Á Vĩnh Long', shortName: 'Vĩnh Long', region: 'Vĩnh Long', inventoryCount: 42 },
  { id: 'tay-nguyen', name: 'BV Xuyên Á Tây Nguyên', shortName: 'Tây Nguyên', region: 'Tây Nguyên', inventoryCount: 33 },
]

const commonDocuments = [
  {
    id: 'doc-01',
    name: 'Hop-dong-mua-sam-2023.pdf',
    type: 'Hợp đồng' as const,
    size: '2,4 MB',
    uploadedAt: '12/03/2023',
  },
  {
    id: 'doc-02',
    name: 'Bien-ban-nghiem-thu.pdf',
    type: 'Nghiệm thu' as const,
    size: '1,8 MB',
    uploadedAt: '28/03/2023',
  },
]

const seedDeviceRecords: Omit<Device, 'branchId' | 'acceptanceDate' | 'warrantyStart'>[] = [
  {
    id: 'dev-001',
    code: 'TBYT-HSTC-001',
    hisCode: 'HIS-92104',
    name: 'Máy thở chức năng cao',
    category: 'Hô hấp',
    model: 'Puritan Bennett 980',
    serial: 'PB980-23-0481',
    manufacturer: 'Medtronic',
    origin: 'Hoa Kỳ',
    manufactureYear: 2023,
    usageDate: '2023-04-05',
    contractDate: '2023-03-12',
    handoverDate: '2023-03-28',
    warrantyEnd: '2028-03-28',
    maintenanceCycle: 6,
    nextMaintenance: '2026-08-24',
    company: hospitalName,
    department: 'Khoa Hồi sức tích cực',
    room: 'ICU 01',
    supplier: 'Công ty TNHH Thiết bị Minh Khang',
    price: 1280000000,
    status: 'Chờ bảo trì',
    shared: true,
    documents: [
      ...commonDocuments,
      {
        id: 'doc-03',
        name: 'Phieu-bao-hanh-PB980.pdf',
        type: 'Bảo hành',
        size: '860 KB',
        uploadedAt: '28/03/2023',
      },
    ],
    lastUpdated: '2026-08-22T08:20:00',
  },
  {
    id: 'dev-002',
    code: 'TBYT-CDHA-014',
    hisCode: 'HIS-88329',
    name: 'Máy siêu âm màu 4D',
    category: 'Chẩn đoán hình ảnh',
    model: 'Voluson E10',
    serial: 'GEV-E10-19384',
    manufacturer: 'GE Healthcare',
    origin: 'Áo',
    manufactureYear: 2022,
    usageDate: '2022-09-16',
    contractDate: '2022-08-02',
    handoverDate: '2022-09-10',
    warrantyEnd: '2027-09-10',
    maintenanceCycle: 6,
    nextMaintenance: '2026-10-12',
    company: hospitalName,
    department: 'Khoa Chẩn đoán hình ảnh',
    room: 'Phòng Siêu âm 02',
    supplier: 'Công ty CP Y tế Việt Pháp',
    price: 3450000000,
    status: 'Đang hoạt động',
    shared: true,
    documents: commonDocuments.slice(0, 1),
    lastUpdated: '2026-08-19T14:10:00',
  },
  {
    id: 'dev-003',
    code: 'TBYT-CDHA-006',
    hisCode: 'HIS-87512',
    name: 'Máy X-quang kỹ thuật số',
    category: 'Chẩn đoán hình ảnh',
    model: 'MULTIX Impact C',
    serial: 'SMX-2206-417',
    manufacturer: 'Siemens Healthineers',
    origin: 'Đức',
    manufactureYear: 2022,
    usageDate: '2022-07-22',
    contractDate: '2022-05-18',
    handoverDate: '2022-07-12',
    warrantyEnd: '2027-07-12',
    maintenanceCycle: 6,
    nextMaintenance: '2026-11-06',
    company: hospitalName,
    department: 'Khoa Chẩn đoán hình ảnh',
    room: 'Phòng X-quang 01',
    supplier: 'Công ty CP Y tế Việt Pháp',
    price: 5890000000,
    status: 'Đang hoạt động',
    shared: false,
    documents: commonDocuments,
    lastUpdated: '2026-08-14T09:45:00',
  },
  {
    id: 'dev-004',
    code: 'TBYT-CC-028',
    hisCode: 'HIS-90117',
    name: 'Máy theo dõi bệnh nhân',
    category: 'Theo dõi bệnh nhân',
    model: 'IntelliVue MX450',
    serial: 'MX450-DE-8290',
    manufacturer: 'Philips',
    origin: 'Đức',
    manufactureYear: 2021,
    usageDate: '2021-12-08',
    contractDate: '2021-10-20',
    handoverDate: '2021-11-29',
    warrantyEnd: '2026-11-29',
    maintenanceCycle: 6,
    nextMaintenance: '2026-09-02',
    company: hospitalName,
    department: 'Khoa Cấp cứu',
    room: 'Buồng cấp cứu 03',
    supplier: 'Công ty TNHH Sao Mai Medical',
    price: 468000000,
    status: 'Đang sửa chữa',
    shared: true,
    documents: commonDocuments.slice(1),
    lastUpdated: '2026-08-22T10:04:00',
  },
  {
    id: 'dev-005',
    code: 'TBYT-HSTC-042',
    hisCode: 'HIS-92189',
    name: 'Bơm tiêm điện',
    category: 'Tiêm truyền',
    model: 'Perfusor Space',
    serial: 'BBP-881-0426',
    manufacturer: 'B. Braun',
    origin: 'Đức',
    manufactureYear: 2024,
    usageDate: '2024-06-15',
    contractDate: '2024-05-04',
    handoverDate: '2024-06-10',
    warrantyEnd: '2027-06-10',
    maintenanceCycle: 12,
    nextMaintenance: '2027-05-18',
    company: hospitalName,
    department: 'Khoa Hồi sức tích cực',
    room: 'ICU 02',
    supplier: 'Công ty TNHH B. Braun Việt Nam',
    price: 78000000,
    status: 'Đang hoạt động',
    shared: true,
    documents: [],
    lastUpdated: '2026-07-25T11:30:00',
  },
  {
    id: 'dev-006',
    code: 'TBYT-XN-011',
    hisCode: 'HIS-86114',
    name: 'Máy xét nghiệm sinh hóa',
    category: 'Xét nghiệm',
    model: 'Cobas c 311',
    serial: 'RC311-198-77',
    manufacturer: 'Roche',
    origin: 'Thụy Sĩ',
    manufactureYear: 2020,
    usageDate: '2020-11-18',
    contractDate: '2020-09-09',
    handoverDate: '2020-11-06',
    warrantyEnd: '2025-11-06',
    maintenanceCycle: 3,
    nextMaintenance: '2026-08-18',
    company: hospitalName,
    department: 'Khoa Xét nghiệm',
    room: 'Phòng Sinh hóa',
    supplier: 'Công ty Roche Việt Nam',
    price: 2180000000,
    status: 'Đang sửa chữa',
    shared: false,
    documents: commonDocuments,
    lastUpdated: '2026-08-21T16:42:00',
  },
  {
    id: 'dev-007',
    code: 'TBYT-NS-003',
    hisCode: 'HIS-87943',
    name: 'Hệ thống nội soi tiêu hóa',
    category: 'Nội soi',
    model: 'EVIS X1 CV-1500',
    serial: 'OLY-X1-4307',
    manufacturer: 'Olympus',
    origin: 'Nhật Bản',
    manufactureYear: 2023,
    usageDate: '2023-10-20',
    contractDate: '2023-08-03',
    handoverDate: '2023-10-12',
    warrantyEnd: '2028-10-12',
    maintenanceCycle: 6,
    nextMaintenance: '2026-12-20',
    company: hospitalName,
    department: 'Khoa Nội soi',
    room: 'Phòng Nội soi 01',
    supplier: 'Công ty TNHH Olympus Việt Nam',
    price: 4320000000,
    status: 'Đang hoạt động',
    shared: false,
    documents: commonDocuments,
    lastUpdated: '2026-08-12T08:00:00',
  },
  {
    id: 'dev-008',
    code: 'TBYT-TM-019',
    hisCode: 'HIS-93408',
    name: 'Máy điện tim 12 kênh',
    category: 'Tim mạch',
    model: 'Cardiofax M ECG-2350',
    serial: 'NK-2350-7302',
    manufacturer: 'Nihon Kohden',
    origin: 'Nhật Bản',
    manufactureYear: 2024,
    usageDate: '2024-02-08',
    contractDate: '2023-12-19',
    handoverDate: '2024-01-29',
    warrantyEnd: '2027-01-29',
    maintenanceCycle: 12,
    nextMaintenance: '2027-01-22',
    company: hospitalName,
    department: 'Khoa Tim mạch',
    room: 'Phòng Điện tim',
    supplier: 'Công ty CP Nihon Kohden Việt Nam',
    price: 286000000,
    status: 'Đang hoạt động',
    shared: true,
    documents: commonDocuments.slice(0, 1),
    lastUpdated: '2026-08-01T10:18:00',
  },
  {
    id: 'dev-009',
    code: 'TBYT-GMHS-008',
    hisCode: 'HIS-84215',
    name: 'Máy gây mê kèm thở',
    category: 'Gây mê hồi sức',
    model: 'Perseus A500',
    serial: 'DRG-A5-12083',
    manufacturer: 'Dräger',
    origin: 'Đức',
    manufactureYear: 2019,
    usageDate: '2019-08-14',
    contractDate: '2019-05-22',
    handoverDate: '2019-08-02',
    warrantyEnd: '2024-08-02',
    maintenanceCycle: 6,
    nextMaintenance: '2026-08-27',
    company: hospitalName,
    department: 'Khoa Gây mê hồi sức',
    room: 'Phòng mổ 03',
    supplier: 'Công ty TNHH Dräger Việt Nam',
    price: 2950000000,
    status: 'Chờ bảo trì',
    shared: false,
    documents: commonDocuments,
    lastUpdated: '2026-08-20T15:03:00',
  },
  {
    id: 'dev-010',
    code: 'TBYT-KSNK-004',
    hisCode: 'HIS-85430',
    name: 'Máy hấp tiệt trùng hơi nước',
    category: 'Kiểm soát nhiễm khuẩn',
    model: 'GSS67H',
    serial: 'GTG-67H-558',
    manufacturer: 'Getinge',
    origin: 'Thụy Điển',
    manufactureYear: 2018,
    usageDate: '2018-06-21',
    contractDate: '2018-03-16',
    handoverDate: '2018-06-08',
    warrantyEnd: '2023-06-08',
    maintenanceCycle: 3,
    nextMaintenance: '2026-09-15',
    company: hospitalName,
    department: 'Khoa Kiểm soát nhiễm khuẩn',
    room: 'Khu tiệt khuẩn trung tâm',
    supplier: 'Công ty CP Thiết bị Y tế Hoàng Gia',
    price: 3260000000,
    status: 'Đang hoạt động',
    shared: false,
    documents: commonDocuments.slice(1),
    lastUpdated: '2026-07-29T09:00:00',
  },
  {
    id: 'dev-011',
    code: 'TBYT-TNT-016',
    hisCode: 'HIS-89666',
    name: 'Máy chạy thận nhân tạo',
    category: 'Lọc máu',
    model: '5008S CorDiax',
    serial: 'FMC-5008-9016',
    manufacturer: 'Fresenius Medical Care',
    origin: 'Đức',
    manufactureYear: 2021,
    usageDate: '2021-07-09',
    contractDate: '2021-04-15',
    handoverDate: '2021-06-28',
    warrantyEnd: '2026-06-28',
    maintenanceCycle: 6,
    nextMaintenance: '2026-10-08',
    company: hospitalName,
    department: 'Khoa Thận nhân tạo',
    room: 'Phòng Lọc máu 02',
    supplier: 'Công ty Fresenius Kabi Việt Nam',
    price: 1120000000,
    status: 'Đang hoạt động',
    shared: true,
    documents: commonDocuments,
    lastUpdated: '2026-08-17T13:12:00',
  },
  {
    id: 'dev-012',
    code: 'TBYT-PT-021',
    hisCode: 'HIS-84109',
    name: 'Đèn mổ treo trần hai nhánh',
    category: 'Phẫu thuật',
    model: 'PowerLED II',
    serial: 'MQ-PL2-7701',
    manufacturer: 'Maquet',
    origin: 'Pháp',
    manufactureYear: 2019,
    usageDate: '2019-09-06',
    contractDate: '2019-06-12',
    handoverDate: '2019-08-27',
    warrantyEnd: '2024-08-27',
    maintenanceCycle: 12,
    nextMaintenance: '2027-02-10',
    company: hospitalName,
    department: 'Khoa Gây mê hồi sức',
    room: 'Phòng mổ 01',
    supplier: 'Công ty CP Thiết bị Y tế Hoàng Gia',
    price: 1850000000,
    status: 'Ngừng sử dụng',
    shared: false,
    documents: [],
    lastUpdated: '2026-08-05T16:20:00',
  },
]

export const seedDevices: Device[] = seedDeviceRecords.map((device, index) => ({
  ...device,
  acceptanceDate: device.handoverDate,
  warrantyStart: device.handoverDate,
  branchId: branches[index % branches.length].id,
  company: hospitalName,
}))

export const seedIncidents: Incident[] = [
  {
    id: 'inc-087',
    code: 'SC-2026-0087',
    deviceId: 'dev-004',
    title: 'Màn hình chập chờn, mất tín hiệu SpO₂',
    description: 'Màn hình nhấp nháy sau khoảng 10 phút sử dụng, đầu đo SpO₂ không nhận tín hiệu.',
    priority: 'Khẩn cấp',
    status: 'Đang xử lý',
    reporter: 'ĐD. Nguyễn Thùy Linh',
    reporterDepartment: 'Khoa Cấp cứu',
    createdAt: '2026-08-22T07:42:00',
    assignee: 'KS. Trần Minh Quân',
    nextActionDate: '2026-08-22',
    hasPhoto: true,
    notes: [
      {
        id: 'note-01',
        author: 'KS. Trần Minh Quân',
        content: 'Đã kiểm tra nguồn và cáp SpO₂, cần thay cáp tín hiệu dự phòng.',
        time: '22/08/2026, 09:15',
      },
    ],
  },
  {
    id: 'inc-086',
    code: 'SC-2026-0086',
    deviceId: 'dev-006',
    title: 'Máy báo lỗi nhiệt độ buồng phản ứng',
    description: 'Mã lỗi E-407 xuất hiện khi chạy mẫu QC đầu ngày.',
    priority: 'Cao',
    status: 'Chờ linh kiện',
    reporter: 'KTV. Phạm Quốc Huy',
    reporterDepartment: 'Khoa Xét nghiệm',
    createdAt: '2026-08-21T15:18:00',
    assignee: 'Roche Việt Nam',
    nextActionDate: '2026-08-24',
    hasPhoto: true,
    notes: [
      {
        id: 'note-02',
        author: 'Phòng TTBYT',
        content: 'Nhà cung cấp xác nhận giao cảm biến nhiệt vào sáng 24/08.',
        time: '22/08/2026, 08:30',
      },
    ],
  },
  {
    id: 'inc-085',
    code: 'SC-2026-0085',
    deviceId: 'dev-001',
    title: 'Cần kiểm tra cảnh báo áp lực đường thở',
    description: 'Cảnh báo áp lực cao xuất hiện không ổn định khi test máy.',
    priority: 'Cao',
    status: 'Mới tiếp nhận',
    reporter: 'BS. Lê Anh Tuấn',
    reporterDepartment: 'Khoa Hồi sức tích cực',
    createdAt: '2026-08-22T10:06:00',
    assignee: 'Chưa phân công',
    nextActionDate: '2026-08-22',
    hasPhoto: false,
    notes: [],
  },
  {
    id: 'inc-084',
    code: 'SC-2026-0084',
    deviceId: 'dev-010',
    title: 'Gioăng cửa buồng hấp rò hơi nhẹ',
    description: 'Phát hiện hơi thoát tại mép dưới cửa trong chu trình 134°C.',
    priority: 'Trung bình',
    status: 'Đang xử lý',
    reporter: 'ĐD. Vũ Ngọc Mai',
    reporterDepartment: 'Khoa Kiểm soát nhiễm khuẩn',
    createdAt: '2026-08-20T11:23:00',
    assignee: 'KS. Nguyễn Đức Anh',
    nextActionDate: '2026-08-25',
    hasPhoto: true,
    notes: [],
  },
  {
    id: 'inc-083',
    code: 'SC-2026-0083',
    deviceId: 'dev-008',
    title: 'Giấy in ECG bị lệch mép',
    description: 'Cuộn giấy lệch khi in báo cáo đủ 12 chuyển đạo.',
    priority: 'Thấp',
    status: 'Đã hoàn tất',
    reporter: 'ĐD. Trần Ngọc Hà',
    reporterDepartment: 'Khoa Tim mạch',
    createdAt: '2026-08-19T08:48:00',
    assignee: 'KS. Trần Minh Quân',
    hasPhoto: false,
    notes: [],
  },
  {
    id: 'inc-082',
    code: 'SC-2026-0082',
    deviceId: 'dev-005',
    title: 'Phím xác nhận phản hồi chậm',
    description: 'Phím OK cần nhấn mạnh hơn bình thường.',
    priority: 'Trung bình',
    status: 'Đã hoàn tất',
    reporter: 'ĐD. Võ Thanh Thảo',
    reporterDepartment: 'Khoa Hồi sức tích cực',
    createdAt: '2026-08-18T14:35:00',
    assignee: 'KS. Nguyễn Đức Anh',
    hasPhoto: true,
    notes: [],
  },
]

export const seedMaintenance: MaintenanceEvent[] = [
  {
    id: 'mnt-01',
    deviceId: 'dev-001',
    type: 'Bảo trì định kỳ',
    date: '2026-08-24',
    time: '08:30',
    provider: 'Công ty TNHH Thiết bị Minh Khang',
    assignee: 'KS. Trần Minh Quân',
    reminderDays: 3,
    status: 'Sắp tới',
    note: 'Kiểm tra bộ lọc, cảm biến lưu lượng và pin dự phòng.',
  },
  {
    id: 'mnt-02',
    deviceId: 'dev-009',
    type: 'Hiệu chuẩn',
    date: '2026-08-27',
    time: '13:30',
    provider: 'Công ty TNHH Dräger Việt Nam',
    assignee: 'KS. Nguyễn Đức Anh',
    reminderDays: 5,
    status: 'Sắp tới',
    note: 'Hiệu chuẩn lưu lượng khí mê và cảm biến O₂.',
  },
  {
    id: 'mnt-03',
    deviceId: 'dev-004',
    type: 'Sửa chữa',
    date: '2026-08-22',
    time: '14:00',
    provider: 'Phòng Trang thiết bị y tế',
    assignee: 'KS. Trần Minh Quân',
    reminderDays: 0,
    status: 'Đang thực hiện',
    note: 'Thay cáp SpO₂ và chạy kiểm thử an toàn điện.',
  },
  {
    id: 'mnt-04',
    deviceId: 'dev-006',
    type: 'Sửa chữa',
    date: '2026-08-24',
    time: '10:00',
    provider: 'Công ty Roche Việt Nam',
    assignee: 'KS. Nguyễn Đức Anh',
    reminderDays: 1,
    status: 'Sắp tới',
    note: 'Thay cảm biến nhiệt buồng phản ứng.',
  },
  {
    id: 'mnt-05',
    deviceId: 'dev-010',
    type: 'Bảo trì định kỳ',
    date: '2026-08-18',
    time: '09:00',
    provider: 'Công ty CP Thiết bị Y tế Hoàng Gia',
    assignee: 'KS. Nguyễn Đức Anh',
    reminderDays: 3,
    status: 'Quá hạn',
    note: 'Chờ xác nhận lịch lại từ khoa sử dụng.',
  },
  {
    id: 'mnt-06',
    deviceId: 'dev-002',
    type: 'Bảo hành',
    date: '2026-08-14',
    time: '08:00',
    provider: 'Công ty CP Y tế Việt Pháp',
    assignee: 'KS. Trần Minh Quân',
    reminderDays: 7,
    status: 'Hoàn tất',
    note: 'Đã kiểm tra đầu dò và cập nhật phần mềm hệ thống.',
  },
]

export const departmentCatalog: { name: string; shortName: string }[] = [
  { name: 'Khoa Hồi sức tích cực', shortName: 'HSTC' },
  { name: 'Khoa Cấp cứu', shortName: 'Cấp cứu' },
  { name: 'Khoa Chẩn đoán hình ảnh', shortName: 'CĐHA' },
  { name: 'Khoa Xét nghiệm', shortName: 'Xét nghiệm' },
  { name: 'Khoa Gây mê hồi sức', shortName: 'GMHS' },
  { name: 'Khoa Tim mạch', shortName: 'Tim mạch' },
  { name: 'Khoa Thận nhân tạo', shortName: 'Thận NT' },
  { name: 'Khoa Kiểm soát nhiễm khuẩn', shortName: 'KSNK' },
  { name: 'Khoa Nội soi', shortName: 'Nội soi' },
  { name: 'Khoa Ngoại tổng quát', shortName: 'Ngoại TQ' },
  { name: 'Khoa Sản', shortName: 'Sản' },
  { name: 'Khoa Nhi', shortName: 'Nhi' },
  { name: 'Phòng Trang thiết bị y tế', shortName: 'TTBYT' },
]

export const slugify = (value: string) =>
  value
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/đ/g, 'd')
    .replace(/Đ/g, 'D')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')

export const departmentId = (branchId: BranchId, name: string) => `dep-${branchId}-${slugify(name)}`

export const seedDepartments: Department[] = branches.flatMap((branch) =>
  departmentCatalog.map((item) => ({
    id: departmentId(branch.id, item.name),
    branchId: branch.id,
    name: item.name,
    shortName: item.shortName,
    head: '',
    phone: '',
  })),
)

export const organizationTree: OrganizationUnit[] = [
  {
    id: 'org-01',
    name: hospitalName,
    type: 'company',
    count: branches.reduce((total, branch) => total + branch.inventoryCount, 0),
    children: branches.map((branch) => ({
      id: `org-${branch.id}`,
      name: branch.name,
      type: 'department',
      count: branch.inventoryCount,
      children: departmentCatalog.map((item) => ({
        id: departmentId(branch.id, item.name),
        name: item.name,
        type: 'room',
        count: 0,
      })),
    })),
  },
]

export const monthlyIncidents = [
  { month: 'T3', count: 12 },
  { month: 'T4', count: 9 },
  { month: 'T5', count: 15 },
  { month: 'T6', count: 10 },
  { month: 'T7', count: 13 },
  { month: 'T8', count: 8 },
]

export const seedPermissions: AccessPermission[] = seedDepartments.map((department, index) => ({
  id: `perm-${department.id}`,
  branchId: department.branchId,
  name: department.name,
  users: 8 + ((index * 7) % 18),
  view: true,
  borrow: index % 4 !== 3,
  approve: department.shortName === 'TTBYT' || index % 5 === 0,
}))

export const defaultUserPassword = 'Xuyena123'

const branchAccountName = (branchId: BranchId) => branches.find((branch) => branch.id === branchId)?.shortName ?? branchId

export const seedUsers: Array<UserAccount & { password: string }> = [
  { id: 'user-admin', username: 'admin', displayName: 'Quản trị hệ thống', role: 'admin', active: true, password: defaultUserPassword },
  ...branches.map((branch) => ({
    id: `user-${branch.id}`,
    username: `moderator-${branch.id}`,
    displayName: `Quản lý ${branch.shortName}`,
    role: 'moderator' as const,
    branchId: branch.id,
    active: true,
    password: defaultUserPassword,
  })),
  ...seedDepartments.map((department) => ({
    id: `user-${department.id}`,
    username: `${slugify(department.shortName)}.${department.branchId}`,
    displayName: `${department.shortName} · ${branchAccountName(department.branchId)}`,
    role: 'department' as const,
    branchId: department.branchId,
    department: department.name,
    active: true,
    password: defaultUserPassword,
  })),
]
